"""All models are imported here so ``Base.metadata`` is complete for Alembic."""

from africasignal.models.assessments import (
    AssessmentInput,
    AssessmentVersion,
    OperatorPolicySeries,
    Situation,
)
from africasignal.models.base import Base
from africasignal.models.claims import Claim
from africasignal.models.evidence import EvidenceDocument, GdeltDiscovery, ReportingOrigin
from africasignal.models.llm_cache import LlmResponseCache
from africasignal.models.measurements import Measurement, MeasurementReview, Series
from africasignal.models.ops import (
    AgentReachCandidate,
    AgentReachTask,
    AuditLog,
    Campaign,
    ChannelPost,
    CommercialControl,
    CommercialDraft,
    ContentContext,
    CreativeVersion,
    DeliveryAggregate,
    DeliveryEvent,
    Event,
    ExternalAgentProfile,
    ExternalAgentTask,
    Feedback,
    Job,
    LlmBudgetReservation,
    LlmCall,
    Operator,
    OperatorSignInFailure,
    Outbox,
    PlacementBooking,
    Setting,
    Sponsor,
    WorkloadControl,
)
from africasignal.models.places import Place, PlaceAlias
from africasignal.models.runtime import JobArchive, JobDeduplication, RateLimitState
from africasignal.models.sources import DiscoveredDomainDecision, Source, SourcePermission
from africasignal.models.users import (
    AccountDeletion,
    AppUser,
    Follow,
    LoginToken,
    Notification,
    Preference,
    UserSession,
)

__all__ = [
    "AccountDeletion",
    "AgentReachCandidate",
    "AgentReachTask",
    "AppUser",
    "AssessmentInput",
    "AssessmentVersion",
    "AuditLog",
    "Base",
    "ChannelPost",
    "Campaign",
    "CommercialControl",
    "CommercialDraft",
    "ContentContext",
    "DeliveryAggregate",
    "DeliveryEvent",
    "CreativeVersion",
    "Claim",
    "DiscoveredDomainDecision",
    "Event",
    "EvidenceDocument",
    "ExternalAgentProfile",
    "ExternalAgentTask",
    "Feedback",
    "Follow",
    "GdeltDiscovery",
    "Job",
    "JobArchive",
    "JobDeduplication",
    "RateLimitState",
    "LlmBudgetReservation",
    "LlmCall",
    "LlmResponseCache",
    "LoginToken",
    "Measurement",
    "MeasurementReview",
    "Notification",
    "Operator",
    "OperatorPolicySeries",
    "OperatorSignInFailure",
    "Outbox",
    "Place",
    "PlaceAlias",
    "PlacementBooking",
    "Preference",
    "ReportingOrigin",
    "Series",
    "Setting",
    "Sponsor",
    "WorkloadControl",
    "Situation",
    "Source",
    "SourcePermission",
    "UserSession",
]
